#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
PIDFILE=/var/run/$DAEMON_NAME.pid

case "$1" in
  start)
    echo "Starting $DAEMON_NAME..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
    ;;
  stop)
    echo "Stopping $DAEMON_NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 5
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
